name: Authentication Workflow

on:
  workflow_call:
    secrets:
      AZURE_CLIENT_ID:
        description: Azure Client Id
        required: true
      AZURE_TENANT_ID:
        description: Azure Tenant Id
        required: true
      AZURE_SUBSCRIPTION_ID:
        description: Azure Subscription Id
        required: true
      AWS_GITHUB_OIDC_ROLE_ARN:
        description: AWS OIDC Role to assume and use as a jump to the execution role
        required: true
      AWS_GITHUB_OIDC_EXECUTION_ROLE_ARN:
        description: AWS Execution role to perform actions in the account
        required: true
    inputs:
      AWS_REGION:
        description: AWS Region - even though a global service - still needs defining
        required: true
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Instance Checks
        run: |
          pwd
          df -h .
          date > testfile
          ls -l 
